@ECHO OFF
SET "base_dir=D:\Vikas_New_Folder\Personal\Educative\source code\"

ECHO Starting Config service...
START "Config service" /D "%base_dir%\config-server" mvn spring-boot:run

ECHO Starting Discovery service...
START "Discovery service" /D "%base_dir%\discovery-service" mvn spring-boot:run

ECHO Starting Gateway service...
START "Gateway service" /D "%base_dir%\gateway-service" mvn spring-boot:run

ECHO Starting Auth service...
START "Auth service" /D "%base_dir%\auth-service" mvn spring-boot:run

ECHO Starting Expense service...
START "Expense service" /D "%base_dir%\expense-service" mvn spring-boot:run

ECHO Starting Income service...
START "Income service" /D "%base_dir%\income-service" mvn spring-boot:run

ECHO All microservices are starting up...
