version: '3.7'

services:

  discovery-service:
    build:
      context: ./discovery-service
    ports:
      - "8761:8761"

  config-service:
    build:
      context: ./config-service
    ports:
      - "8888:8888"
    environment:
      "eureka.client.serviceUrl.defaultZone": "http://discovery-service:8761/eureka"

  auth-service:
    build:
      context: ./auth-service
    ports:
      - "8555:8555"
    environment:
      "eureka.client.serviceUrl.defaultZone": "http://discovery-service:8761/eureka"

  gateway-service:
    build: ./gateway-service
    ports:
      - "8765:8765"
    environment:
      "eureka.client.serviceUrl.defaultZone": "http://discovery-service:8761/eureka"
      "spring.cloud.discovery.client.simple.instances.auth-service[0].uri": "http://auth-service:8555"
      "spring.cloud.discovery.client.simple.instances.expense-service[0].uri": "http://expense-service:8081"
      "spring.cloud.discovery.client.simple.instances.income-service[0].uri": "http://income-service:8082"

  expense-service:
    build:
      context: ./expense-service
    environment:
      "spring.datasource.url": "jdbc:mysql://mysql-db:3310/personal_finance"
      "spring.datasource.username": "pf_user"
      "spring.datasource.password": "pf_pwd"
    ports:
      - "8081:8080"
    depends_on:
      - mysql-db

  income-service:
    build:
      context: ./income-service
    environment:
      "spring.datasource.url": "jdbc:mysql://mysql-db:3310/personal_finance"
      "spring.datasource.username": "pf_user"
      "spring.datasource.password": "pf_pwd"
    ports:
      - "8082:8080"
    depends_on:
      - mysql-db

  report-service:
    build:
      context: ./report-service
    environment:
      "spring.datasource.url": "jdbc:mysql://mysql-db:3310/personal_finance"
      "spring.datasource.username": "pf_user"
      "spring.datasource.password": "pf_pwd"
    ports:
      - "8083:8080"
    depends_on:
      - mysql-db

  personal-finance-ui:
    build:
      context: ./personal-finance-ui/personal-finance-app
    ports:
      - "4200:80"
    depends_on:
      - auth-service

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: personal_finance
      MYSQL_USER: pf_user
      MYSQL_PASSWORD: pf_pwd
    ports:
      - "3310:3306"
    volumes:
      - ./db/per_fin_db.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data-folder:/var/lib/mysql

volumes:
  mysql-data-folder: