#MySQL Database
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/personal_finance
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: "expense-service"
server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka/"
