spring:
  application:
    name: discovery-service
#  security:
#    basic:
#      enabled: true
#    user:
#      name: eurekauser
#      password: eureka!
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true